# Setup
title:               'Marta C Couto'
tagline:             'Postdoctoral researcher, University of Amsterdam'
description:         ''
url:                 https://martagccouto.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

social:
  twitter: "https://x.com/martaccouto"
  github: "https://github.com/martagccouto"
  researchgate: "https://www.researchgate.net/profile/Marta-Couto-3"
  googlescholar: "https://scholar.google.de/citations?user=ZbYvBcUAAAAJ&hl=en"
  linkedin: "https://www.linkedin.com/in/marta-c-couto/"